### ISSUE TITLE
No module named scapy.all

### ISSUE THREAD

**Issue by neildeadman** [AgustinPelaez/wifi-presence-detector#1]
Having followed your setup guide, I ran the script and I get:

`Traceback (most recent call last):
  File "presence_detector.py", line 2, in <module>
    from scapy.all import *
ImportError: No module named scapy.all`

I am running this on CentOS 7. Let me know if you need anything else.

**Comment by AgustinPelaez** [comment]
Hey Neil - did you install Scapy first? I'd recommend checking out https://pypi.org/project/scapy/ to make sure Scapy is correctly installed.

**Comment by neildeadman** [comment]
I did. I eventually found that the path where scapy module was placed on my system wasn't in the sys.os.path when I imported os, so I appended my path which worked.
